### ISSUE TITLE
[FEA]cusignal exmaple notebook

### ISSUE THREAD

**Issue by yidong72** [NVIDIA/fsi-samples#140]
convert this notebook 
https://github.com/rapidsai/cusignal/blob/branch-21.08/notebooks/sdr/sdr_integration.ipynb
to greenflow way.

**Comment by avolkov1** [comment]
Done in merge #141. Refer to notebook:
<https://github.com/NVIDIA/fsi-samples/blob/develop/gQuant/plugins/cusignal_plugin/notebooks/sdr_examples.ipynb>
