### ISSUE TITLE
[FEA] Remove mentions to 'framework' from gQuant project

### ISSUE THREAD

**Issue by miguelusque** [NVIDIA/fsi-samples#25]
Hi,

Some notebooks refer to gQuant as a _framework_.

I think we should avoid that word, and use alternative expressions such as 'gQuant is a set of examples' or similar.

Regards,
Miguel

**Comment by avolkov1** [comment]
The repo has been renamed to `fsi-samples` and the top-level project no longer implies framework. The core part that used to be called "gQuant" is now "greenflow". The "gQuant" part is a plugin package with notebooks for fsi-examples, and not a framework.
