### ISSUE TITLE
[FEA] factor out the translate_column logic to let user define customized column setup

### ISSUE THREAD

**Issue by yidong72** [NVIDIA/fsi-samples#69]
**Is your feature request related to a problem? Please describe.**
The translate_column is useful but it could be factored out to just be a node helper function and we can add examples of how to use that in columns_setup API. People can then use it or implement their own logic for dynamic columns manipulation. By factoring it out we wouldn't be coupling a mini language (DSL - domain-specific lang.) to the node class to manipulate columns.

**Comment by avolkov1** [comment]
No longer relevant. The metadata API has various hooks which can set column data types. Refer to `NodeExtensionMixin::_resolve_meta` and `NodeTaskGraphExtensionMixin::meta_setup_ext`. Any additional custom logic can be handled in the override of 'Node::meta_setup`.
